Repository codestates-seb/seb45_main_019, pull requests merged in 2023-09, with the labels that each got.

#84 [feat] Eslint/prettier
  README.md
  client/.eslintrc.json
  client/.prettierrc.json
  client/tsconfig.json
  server/init
  server/init.txt
Labels: Front, Feature

#86 [FE] Enter 컴포넌트 스타일 완료, 기타사항 수정
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/public/images/chapter1.png
  client/public/images/main_logo1.png
  client/public/images/main_logo2.png
  client/public/images/main_logo3.png
  client/src/App.tsx
  client/src/components/Body/Body.tsx
  client/src/components/Enter/Enter.styled.js
  client/src/components/Enter/Enter.tsx
  client/src/components/GuideBook/GuideBook.tsx
  client/src/components/Nav/Nav.tsx
  client/src/index.tsx
  client/src/pages/Main/MainPage.tsx
  client/src/redux/store.ts
  client/src/style/Global.styled.js
  client/src/types/image.d.ts
  client/tsconfig.json
Labels: Front, Style

#87 [feat] Member CRUD 구현
  server/.gradle/8.2.1/checksums/checksums.lock
  server/.gradle/8.2.1/dependencies-accessors/dependencies-accessors.lock
  server/.gradle/8.2.1/executionHistory/executionHistory.bin
  server/.gradle/8.2.1/executionHistory/executionHistory.lock
  server/.gradle/8.2.1/fileHashes/fileHashes.bin
  server/.gradle/8.2.1/fileHashes/fileHashes.lock
  server/.gradle/8.2.1/fileHashes/resourceHashesCache.bin
  server/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  server/build/classes/java/main/ILearn/global/Response/ApiResponse.class
  server/build/classes/java/main/ILearn/global/Response/ApiResponseException.class
  server/build/classes/java/main/ILearn/global/exception/DuplicateFieldException.class
  server/build/classes/java/main/ILearn/global/exception/ExceptionAdvice.class
  server/build/classes/java/main/ILearn/member/controller/MemberController.class
  server/build/classes/java/main/ILearn/member/dto/MemberPostDto.class
  server/build/classes/java/main/ILearn/member/dto/MemberResponseDto$Data.class
  server/build/classes/java/main/ILearn/member/dto/MemberResponseDto.class
  server/build/classes/java/main/ILearn/member/entity/Member$MemberStatus.class
  server/build/classes/java/main/ILearn/member/entity/Member.class
  server/build/classes/java/main/ILearn/member/mapper/MemberMapperImpl.class
  server/build/classes/java/main/ILearn/member/repository/MemberRepository.class
  server/build/classes/java/main/ILearn/member/service/MemberService.class
  server/build/generated/sources/annotationProcessor/java/main/ILearn/member/mapper/MemberMapperImpl.java
  server/build/tmp/compileJava/compileTransaction/stash-dir/MemberController.class.uniqueId0
  server/build/tmp/compileJava/compileTransaction/stash-dir/MemberController.class.uniqueId3
  server/build/tmp/compileJava/compileTransaction/stash-dir/MemberMapper.class.uniqueId0
  server/build/tmp/compileJava/compileTransaction/stash-dir/MemberMapperImpl.class.uniqueId1
  server/build/tmp/compileJava/compileTransaction/stash-dir/MemberMapperImpl.java.uniqueId2
  server/build/tmp/compileJava/previous-compilation-data.bin
  server/src/main/java/ILearn/global/Response/ApiResponse.java
  server/src/main/java/ILearn/global/Response/ApiResponseException.java
  server/src/main/java/ILearn/global/exception/DuplicateFieldException.java
  server/src/main/java/ILearn/global/exception/ExceptionAdvice.java
  server/src/main/java/ILearn/member/controller/MemberController.java
  server/src/main/java/ILearn/member/dto/MemberPostDto.java
  server/src/main/java/ILearn/member/dto/MemberResponseDto.java
  server/src/main/java/ILearn/member/entity/Member.java
  server/src/main/java/ILearn/member/repository/MemberRepository.java
  server/src/main/java/ILearn/member/service/MemberService.java
Labels: Feature, Level. 0, Back, Member

#88 [FE] Nav 전역 상태 완료
  client/public/images/chapter2.png
  client/src/App.tsx
  client/src/common/data/chapterData.ts
  client/src/common/data/index.ts
  client/src/components/Enter/Enter.styled.js
  client/src/components/Enter/Enter.tsx
  client/src/components/GuideBook/GuideBook.tsx
  client/src/components/Nav/Nav.styled.js
  client/src/components/Nav/Nav.tsx
  client/src/components/Nav/NavItem.tsx
  client/src/interfaces/Chapter.interface.ts
  client/src/pages/Main/MainPage.styled.js
  client/src/pages/Main/MainPage.tsx
  client/src/pages/Word/WordPage.styled.js
  client/src/redux/hooks.ts
  client/src/redux/slices/chapter.ts
  client/src/redux/store.ts
  client/src/style/App.styled.js
  client/src/style/Global.styled.js
Labels: Front, Feature, Level. 0, Chapter

#89 [feat]Header 추가
  client/src/components/Header/Header.tsx
  client/src/pages/Main/MainPage.tsx
Labels: Front, Feature

#96 [FE] Header 스타일 수정, Link href 수정
  .github/workflows/ci_cd.yml
  client/src/App.tsx
  client/src/common/utils/api.ts
  client/src/components/Enter/Enter.tsx
  client/src/components/Header/Header.tsx
  client/src/components/Nav/Nav.tsx
  client/src/pages/Learn/Learn.tsx
  client/src/pages/Main/MainPage.tsx
  client/src/pages/SignIn/SignIn.tsx
  client/src/pages/SignUp/SignUp.tsx
  client/src/style/Global.styled.js
Labels: Front, Fix, Style

#99 Feat/signin
  .github/workflows/fe_deploy.yml
  client/package.json
  client/public/images/main-logo.png
  client/public/images/sign.png
  client/src/pages/SignIn/SignIn.tsx
  client/src/pages/SignUp/Input.tsx
  client/src/pages/SignUp/SignUp.tsx
Labels: Front, Style

#103 Guidebook
  client/src/components/GuideBook/GuideBook.tsx
Labels: Front, Feature

#104 Feat/speaker
  client/src/common/utils/speak.ts
  client/src/components/Speaker/Speaker.tsx
Labels: Front, Feature

#109 [FE] 디자인 수정 작업
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/images/chapter1.png
  client/public/images/chapter2.png
  client/public/images/main_logo1.png
  client/public/images/main_logo2.png
  client/public/images/main_logo3.png
  client/src/App.tsx
  client/src/common/data/chapterData.ts
  client/src/components/Enter/Enter.tsx
  client/src/components/Enter/MainProgress.tsx
  client/src/components/GuideBook/GuideBook.tsx
  client/src/components/Header/Header.tsx
  client/src/components/Nav/Nav.tsx
  client/src/components/Nav/NavItem.tsx
  client/src/pages/Main/MainPage.tsx
  client/src/style/Global.styled.js
Labels: Front, Fix, Style

#115 [FE] 챕터 전체 목록 조회 API 연결, 상태 관리
  client/public/index.html
  client/src/App.tsx
  client/src/common/data/chapterData.ts
  client/src/components/Enter/Enter.tsx
  client/src/components/Enter/MainProgress.tsx
  client/src/components/GuideBook/GuideBook.tsx
  client/src/components/Header/Header.tsx
  client/src/components/Nav/MainNavItem.tsx
  client/src/components/Nav/Nav.tsx
  client/src/components/Nav/NavItem.tsx
  client/src/components/Nav/WordNavItem.tsx
  client/src/components/Questions/Progress.tsx
  client/src/components/Questions/QTypeChoice.tsx
  client/src/components/Questions/QTypeTyping.tsx
  client/src/index.tsx
  client/src/interfaces/Chapter.interface.ts
  client/src/pages/Learn/Learn.tsx
  client/src/pages/Main/MainPage.tsx
  client/src/pages/Questions/Questions.tsx
  client/src/pages/SignIn/SignIn.tsx
  client/src/pages/Word/WordPage.tsx
  client/src/redux/slices/chapter.ts
  client/tsconfig.json
Labels: Front, Feature, Level. 0, Member, Style, Chapter

#116 Feat/SelectButton
  client/src/common/data/learningData.ts
  client/src/components/Button/SelectButton.tsx
  client/src/interfaces/Learning.interface.ts
Labels: Front, Feature

#117 Feat/word
  client/src/components/GuideBook/GuideBook.tsx
  client/src/components/Word/Word.api.ts
  client/src/components/Word/Word.tsx
Labels: Front, Feature, Level. 0, Test

#128 [feat]회원탈퇴예외 반환 구현
  server/.gradle/8.2.1/executionHistory/executionHistory.bin
  server/.gradle/8.2.1/executionHistory/executionHistory.lock
  server/.gradle/8.2.1/fileHashes/fileHashes.bin
  server/.gradle/8.2.1/fileHashes/fileHashes.lock
  server/.gradle/8.2.1/fileHashes/resourceHashesCache.bin
  server/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  server/.gradle/buildOutputCleanup/outputFiles.bin
  server/.gradle/file-system.probe
  server/.idea/dataSources.local.xml
  server/.idea/dataSources/034d8e8e-43a2-477a-8fb6-8c198645f7e0.xml
  server/build/classes/java/main/ILearn/global/auth/handler/MemberAuthenticationSuccessHandler.class
  server/build/classes/java/main/ILearn/member/controller/MemberController.class
  server/build/classes/java/main/ILearn/member/dto/MemberResponseDto.class
  server/build/classes/java/main/ILearn/member/entity/Member$MemberStatus.class
  server/build/classes/java/main/ILearn/member/entity/Member.class
  server/build/classes/java/main/ILearn/member/mapper/MemberMapperImpl.class
  server/build/classes/java/main/ILearn/member/service/MemberService.class
  server/build/generated/sources/annotationProcessor/java/main/ILearn/member/mapper/MemberMapperImpl.java
  server/build/generated/sources/annotationProcessor/java/main/ILearn/question/mapper/QuestionMapperImpl.java
  server/build/generated/sources/annotationProcessor/java/main/ILearn/word/mapper/WordMapperImpl.java
  server/build/tmp/compileJava/previous-compilation-data.bin
  server/src/main/java/ILearn/global/auth/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/ILearn/member/controller/MemberController.java
  server/src/main/java/ILearn/member/dto/MemberResponseDto.java
  server/src/main/java/ILearn/member/entity/Member.java
  server/src/main/java/ILearn/member/service/MemberService.java
Labels: Feature, Level. 0, Back, Member

#130 Feat/result
  client/src/common/utils/pointCalculator.ts
  client/src/components/Enter/Enter.tsx
  client/src/components/GuideBook/GuideBook.tsx
  client/src/components/Word/AddWord.tsx
  client/src/components/Word/Word.tsx
  client/src/interfaces/Chapter.interface.ts
  client/src/pages/Result/Progress.tsx
  client/src/pages/Result/Result.tsx
  client/src/pages/Result/ResultContent.tsx
Labels: Front, Feature, Fix, Learning

#136 [FE] 챕터 진행상황, 문제 조회 api 연결 작업
  .github/workflows/fe_deploy.yml
  client/public/index.html
  client/src/common/data/chapterData.ts
  client/src/common/data/learningData.ts
  client/src/common/utils/localStorageFuncs.ts
  client/src/common/utils/pointCalculator.ts
  client/src/common/utils/speak.ts
  client/src/components/Enter/Enter.tsx
  client/src/components/Header/Header.tsx
  client/src/components/Nav/Nav.tsx
  client/src/components/Nav/WordNavItem.tsx
  client/src/components/Progress/MainProgress.tsx
  client/src/components/Progress/QuestionProgress.tsx
  client/src/components/Questions/Progress.tsx
  client/src/components/Word/Word.tsx
  client/src/interfaces/Chapter.interface.ts
  client/src/interfaces/Learning.interface.ts
  client/src/pages/Main/MainPage.tsx
  client/src/pages/MyPage/MyPage.tsx
  client/src/pages/Questions/Questions.tsx
  client/src/queries/useAllChapterQuery.ts
  client/src/queries/useAllUserChapterQuery.ts
  client/src/redux/slices/chapter.ts
  client/src/redux/slices/user.ts
Labels: Front, Feature, Level. 0, Learning, Manage, Chapter

#138 Result, QType3
  client/src/App.tsx
  client/src/components/Button/SelectButton.tsx
  client/src/components/Progress/Progress.tsx
  client/src/components/Progress/ResultProgress.tsx
  client/src/components/Questions/QTypeTyping.tsx
  client/src/index.tsx
  client/src/pages/Result/ResultContent.tsx
Labels: Front, Feature, Fix, Learning

#142 가이드북 구현, 회원가입, 로그인 예외처리
  client/src/common/data/wordData.ts
  client/src/components/GuideBook/GuideBook.tsx
  client/src/components/Speaker/Speaker.tsx
  client/src/components/Word/AddWord.tsx
  client/src/components/Word/Word.tsx
  client/src/index.tsx
  client/src/interfaces/Word.interface.ts
  client/src/pages/SignIn/SignIn.tsx
  client/src/pages/SignUp/SignUp.tsx
  client/src/queries/useWordQuery.ts
Labels: Front, Feature, Fix, Level. 0, Learning, Word

#144 Mypage
  client/package-lock.json
  client/package.json
  client/src/common/utils/api.ts
  client/src/pages/MyPage/MyPage.tsx
Labels: Front, Feature, Level. 0

#148 Mypage
  client/src/pages/MyPage/MyPage.tsx
Labels: Front, Feature

#143 [FE] 문제풀이 페이지 작업
  client/src/common/utils/api.ts
  client/src/common/utils/pointCalculator.ts
  client/src/components/Button/SelectButton.tsx
  client/src/components/Enter/Enter.tsx
  client/src/components/Header/Header.tsx
  client/src/components/Progress/MainProgress.tsx
  client/src/components/Progress/Progress.tsx
  client/src/components/Progress/QuestionProgress.tsx
  client/src/components/Questions/QTypeChoice.tsx
  client/src/components/Questions/QTypeTyping.tsx
  client/src/index.tsx
  client/src/pages/Main/MainPage.tsx
  client/src/pages/Questions/Questions.tsx
  client/src/queries/useLearningMutation.ts
  client/src/redux/slices/chapter.ts
  client/src/redux/slices/user.ts
Labels: Front, Feature, Level. 0, Question

#162 [FE] 비회원 문제풀이 patch , 테마 추가
  client/package-lock.json
  client/src/App.tsx
  client/src/common/utils/api.ts
  client/src/common/utils/localStorageFuncs.ts
  client/src/common/utils/pointCalculator.ts
  client/src/components/GuideBook/GuideBook.tsx
  client/src/components/Header/Header.tsx
  client/src/components/Nav/Nav.tsx
  client/src/components/Nav/WordNavItem.tsx
  client/src/components/Progress/MainProgress.tsx
  client/src/components/Progress/ResultProgress.tsx
  client/src/components/Speaker/Speaker.tsx
  client/src/components/Word/Word.tsx
  client/src/index.tsx
  client/src/pages/Main/MainPage.tsx
  client/src/pages/MyPage/MyPage.tsx
  client/src/pages/Questions/Questions.tsx
  client/src/pages/Result/ResultContent.tsx
  client/src/pages/SignIn/SignIn.tsx
  client/src/pages/SignUp/SignUp.tsx
  client/src/queries/useSignUpMutation.ts
Labels: Front, Level. 0, Style, Question

#165 [feat] 단어장 페이지 수정
  client/src/common/utils/api.ts
  client/src/pages/Word/WordPage.tsx
Labels: Front

#167 [FE] 메인, 단어, 결과창 디자인 수정
  client/src/components/GuideBook/GuideBook.tsx
  client/src/components/Progress/MainProgress.tsx
  client/src/components/Progress/ResultProgress.tsx
  client/src/components/Questions/QTypeChoice.tsx
  client/src/components/Word/Word.tsx
  client/src/index.tsx
  client/src/pages/Result/ResultContent.tsx
Labels: Front, Style

#170 [feat][fix] Alert -> Dialog로 교체, 로그인 에러 데이터 경로 수정
  client/src/common/utils/speak.ts
  client/src/components/Button/SelectButton.tsx
  client/src/components/Dialogs/AlertDialog.tsx
  client/src/components/Dialogs/ConfirmDialog.tsx
  client/src/components/Dialogs/DialogInterface.ts
  client/src/components/Header/Header.tsx
  client/src/components/Word/AddWord.tsx
  client/src/pages/SignIn/SignIn.tsx
  client/src/pages/SignUp/SignUp.tsx
  client/src/pages/Word/WordPage.tsx
Labels: Front, Feature, Fix, Member, Word, Global
